version: "3.8"

services:
  trading-robot:
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    ports:
      - "2112:2112"

  prometheus:
    image: prom/prometheus:v2.35.0
    volumes:
      - ../configs/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - trading-robot
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:8.2.6
    volumes:
      - ../.grafana:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
